sudo: required
group: deprecated-2017Q4
language: python
python:
    - "3.10"
    - "3.9"
    - "3.8"
env:
    - CKANVERSION=2.9
install:
    - bash bin/travis-build.bash
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
services:
    - redis-server
    - postgresql
script: sh bin/travis-run.sh
before_install:
    - pip install codecov
after_success:
    - codecov
